name: base
channels:
  - conda-forge
dependencies:
- aiohttp[speedups]
- biopython
- pytest
- pytest-asyncio
- python-build
- twine
- setuptools_scm
- pytest-cov
- grayskull
- conda-build
- anaconda-client
- conda-utils
- bioconda-build