{% set name = "automlst.engine" %}
{% set version = "0.5.2.dev2+gde36956" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file:///workspaces/automlst.engine/dist/automlst_engine-0.5.2.dev2%2Bgde36956.tar.gz
  sha256: 2dee4910744f063b7ec5c923bbf369c23151c82cc59b8b99da19e162414ba61d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.11
    - biopython
    - aiohttp

test:
  imports:
    - automlst
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A library to rapidly fetch fetch MLST profiles given sequences for various diseases.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RealYHD
